#ifndef SGESP32EPAPER_CFG
#define SGESP32EPAPER_CFG

#define LANGUAGE_GERMAN 0
#define LANGUAGE_ENGLISH 1

#define LANGUAGE LANGUAGE_ENGLISH

#define DEFAULT_WLAN_SSID "Skynet"
#define DEFAULT_WLAN_PASSWORD "ilikehumans"

#define MODBUS_SERVER_IP_1_OCT 192
#define MODBUS_SERVER_IP_2_OCT 168
#define MODBUS_SERVER_IP_3_OCT 0
#define MODBUS_SERVER_IP_4_OCT 180

#define SWVERSION "0.1.0"


#endif
